final_project_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls', namespace='mysite')),
    path('user/', include('users_app.urls', namespace='users_app')),
]

mysite/urls.py
from django.urls import path
from .views import get_data_use_axios, index
from .views import (CreateTrigger,
                    TriggerListView,
                    DeleteTriggerView,
                    UpdateTriggerView,
                    IndexView
                    )

app_name = 'mysite'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('trigger/', CreateTrigger.as_view(), name='trigger'),
    path('get_data/', get_data_use_axios, name='for_axios'),
    path('trigger_list/', TriggerListView.as_view(), name='trigger_list'),
    path('delete_trigger/<int:pk>', DeleteTriggerView.as_view(), name='delete_trigger'),
    path('update_trigger/<int:pk>', UpdateTriggerView.as_view(), name='update_trigger')
]

users_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'users_app'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users_app/login.html'), name='login'),
    # next_page = должна содержать url куда будет произведен редирект, после логаута
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('users_app:login')), name='logout'),
]

mysite/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
# Create your models here.
import datetime
from mysite.price_com import price


# class Bitcoin(models.Model):
#     trigger_price = models.IntegerField(
#         verbose_name='Триггер'
#     )
#     pair = models.ForeignKey
#
#     def get_absolute_url(self):
#         return reverse('mysite:index')


# from mysite.signals import Alert
#
# post_save.connect(Alert, sender=Bitcoin)


class Symbol(models.Model):
    symbol = models.CharField(
        max_length=256
    )
    price = models.DecimalField(
        blank=True,
        null=True,
        max_digits=15,
        decimal_places=2,
    )
    last_update = models.DateTimeField()
    pic_link = models.CharField(
        max_length=1024,
        null=True,
        blank=True
    )

    def get_latest_data(self):
        if (datetime.datetime.now().replace(tzinfo=None) - self.last_update.replace(tzinfo=None)).total_seconds() > 5:
            self.update_data()
        return self.price, self.pic_link

    def update_data(self):
        new_data = price(self.symbol)
        new_data = float(new_data.get('price'))
        new_data = float('{:.3f}'.format(new_data))
        self.price = new_data
        self.last_update = datetime.datetime.now()
        self.save()

    def __str__(self):
        return f'{self.symbol}'


class Trigger(models.Model):
    trigger_price = models.IntegerField(
        verbose_name='Price Alert'
    )
    pair = models.ForeignKey(
        Symbol,
        on_delete=models.DO_NOTHING,
        null=True,
        verbose_name='pair'
    )
    telegram_id = models.IntegerField(
        verbose_name='telegram_id',
        blank=True,
        null=True,
    )

    def get_absolute_url(self):
        return reverse('mysite:index')

    def __str__(self):
        return f'{self.trigger_price} {self.pair}'


from mysite.signals import Alert

post_save.connect(Alert, sender=Trigger)

users_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.PROTECT,
        verbose_name='user_profile'
    )
    id = models.AutoField(
        verbose_name='id',
        primary_key=True,

    )

    # def __getattribute__(self, name):
    #
    #     if name == 'telegram_id':
    #         return self.telegram_id
    #
    #     else:
    #         return object.__getattribute__(self, name)
    def __str__(self):
        print(self.__getattribute__('telegram_id'))
        return f'{self.user.username} {self.user.email}'

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
        ordering = (
            'id',
        )

mysite/forms.py
from django import forms
from .models import Trigger


class TriggerForm(forms.ModelForm):
    class Meta:
        model = Trigger
        fields = '__all__'

mysite/views.py
from django.contrib.sites import requests
from django.shortcuts import render
from mysite.price_com import symbol, price
import requests
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    TemplateView
)
from .forms import TriggerForm
from .models import Trigger, Symbol
from django.template import Context
from .compare import price
from django.urls import reverse_lazy, reverse


class CreateTrigger(CreateView):
    model = Trigger
    template_name = 'mysite/trigger.html'
    form_class = TriggerForm


class TriggerListView(ListView):
    model = Trigger
    template_name = 'mysite/trigger_list.html'
    context_object_name = 'trigger_list'


class UpdateTriggerView(UpdateView):
    model = Trigger
    template_name = 'mysite/trigger.html'
    form_class = TriggerForm


class DeleteTriggerView(DeleteView):
    template_name = 'mysite/confirm_delete.html'
    model = Trigger
    success_url = reverse_lazy('mysite:trigger_list')


def get_latest_data(symbols: tuple):
    symbols = Symbol.objects.filter(symbol__in=symbols)
    data = {f'{symbol.symbol}': symbol.get_latest_data() for symbol in symbols}
    return data


def index(request):
    return render(request, 'mysite/base.html', context=None)


class IndexView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('users_app:login')
    template_name = 'mysite/base.html'


def get_data_use_axios(request):
    data = get_latest_data(('BTCUSDT', 'ETHUSDT', 'LTCUSDT', 'XRPUSDT', 'XMRUSDT', 'ZECUSDT'))
    return JsonResponse(data)

users_app/views.py
from django.shortcuts import render

# Create your views here.

mysite/templates/mysite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css">
  <meta charset="utf-8">
  <title>Cryptocurrency Pricing Application</title>
</head>
  <body>
  {% block body %}
  <a href="{% url 'mysite:trigger' %}"><img src="https://image.flaticon.com/icons/svg/1156/1156949.svg" width="25" height="25"></a>
  {% verbatim %}
    <div class="container" id="app">
      <h3 class="text-center">Cryptocurrency Pricing</h3>
      <div class="columns medium-4" v-for="(result, index) in results">
        <div class="card">
          <div class="card-section">
              <img :src="result[1]" width="150" height="150">
            <p> {{index}} </p>
          </div>
          <div class="card-divider">
            {{ result[0] }}
          </div>
        </div>
      </div>
    </div>
    {% endverbatim %}
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="/static/mysite/js/update_price.js"></script>
  </body>
{% endblock %}
</html>

mysite/templates/mysite/confirm_delete.html
{% extends 'mysite/base.html' %}
{% block title %}
  Удаление продукта
{% endblock %}
{% block body %}
  <div class="col-lg-6 offset-3">
    <form id="confirm_delete" method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      Вы действительно хотите удалить "{{ object }}"?
      <input type="submit" value="Ок" />
      <a href="{% url 'mysite:update_trigger' object.id %}">Отмена</a>
    </form>
  </div>
{% endblock %}

mysite/templates/mysite/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Site</title>
</head>
<body>

</body>
</html>

mysite/templates/mysite/trigger.html
{% extends 'mysite/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<form id="trigger_form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
<button type="submit">
OK
</button>
</form>
    {% if form.instance.id %}
    <a href="{% url 'mysite:delete_trigger' form.instance.id %}">Delete</a>
    {% endif %}
<a href="{% url 'mysite:trigger_list' %}">List of notifications</a>
{% endblock %}
</body>
</html>

mysite/templates/mysite/trigger_list.html
{% extends 'mysite/base.html' %}
{% block body %}
    <ol>
    {% for trigger in trigger_list  %}
    <li>
        <a href="{% url 'mysite:update_trigger' trigger.id %}">{{ trigger }}</a>
        <a href="{% url 'mysite:delete_trigger' trigger.id %}">Delete notification</a>
    </li>
    {% endfor %}
    </ol>
{% endblock %}

users_app/templates/users_app/login.html
{% extends 'mysite/base.html' %}
{% load static %}
{% block title %}
  Страница авторизации
{% endblock %}
{% block body %}
    <div class="col-lg-4 offset-4">
      {% if form.errors %}
          <p>Пароль или логин не верны</p>
      {% endif %}
      <form id="login_form" method="post"
            action="{% url 'users_app:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button id="sub_btn" name="submit">Вход</button></p>
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      </form>
    </div>
{% endblock %}